defaults:
  - _self_
  - model: small
  - override hydra/launcher: submitit_slurm

ngpus: 4
tokens: 256

training:
  batch_size: 512
  accum: 1
  n_iters: 1500001
  snapshot_freq: 50000
  log_freq: 50
  eval_freq: 100
  snapshot_freq_for_preemption: 2000
  weight: standard
  snapshot_sampling: True
  ema: 0.9999

data:
  name: "SEM_L512_V256"
  train: "/network/scratch/l/lavoiems/datasets/SEM_L512_V256"
  valid: "/network/scratch/l/lavoiems/datasets/SEM_L512_V256"
  cache_dir: data
  hf_dataset: True

graph:
  type: absorb
  file: data
  report_all: False

noise:
  type: loglinear
  sigma_min: 1e-4
  sigma_max: 20

sampling:
  predictor: euler
  steps: 128
  noise_removal: True

eval:
  batch_size: 512
  perplexity: True
  perplexity_batch_size: 32

optim:
  weight_decay: 0
  optimizer: AdamW
  lr: 3e-4
  beta1: 0.9
  beta2: 0.999
  eps: 1e-8
  warmup: 2500
  grad_clip: 1.


hydra:
  run:
    dir: ${oc.env:SCRATCH}/exp/${data.name}-${model.name}/0
  sweep:
    dir: ${oc.env:SCRATCH}/exp/${data.name}-${model.name}/
  launcher:
    timeout_min: 1440
    partition: 60
    mem_gb: 48
    cpus_per_task: 8
    gpus_per_node: ${ngpus}
